import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 1,
  },
  columnGrid: {
    borderWidth: 0.7,
    borderColor: '#1f1f1f',
    position: 'relative',
    zIndex: 2,
    height: 110,
    width: '33%',
    marginBottom: '1%',
    borderRadius: 2,
  },
  columnList: {
    height: 150,
    paddingTop: 10,
    paddingBottom: 25,
    marginBottom: '5%',
    width: '100%',
    borderRadius: 8,
    flexDirection: 'row',
    borderWidth: 0.7,
    borderColor: '#1f1f1f',
    position: 'relative',
    zIndex: 2,
  },
  options: {
    position: 'absolute',
    zIndex: 3,
    height: 30,
    width: 30,
    borderRadius: 50,
    right: '0%',
    marginRight: -5,
    marginTop: 5,
  },
  modal: {
    backgroundColor: 'white',
    height: 65,
    width: 80,
    position: 'relative',
    zIndex: 10,
    right: 60,
    borderRadius: 4,
    padding: 5,
    marginTop: 7,
    borderWidth: 0.3,
    borderColor: '#1f1f1f',
  },
  text: {
    fontSize: 13,
    fontFamily: 'regular',
    padding: 5,
  },
  search: {
    marginTop: 20,
    textAlign: 'center',
    width: 250,
    padding: 20,
    height: 60,
    borderWidth: 0.7,
    borderColor: '#1f1f1f',
    borderRadius: 8,
  },
  textSearch: {
    textAlign: 'center',
    fontFamily: 'bold',
    fontSize: 15,
  },
});

export default styles;
