import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  line: {
    width: "150%",
    height: 0.5,
    left: "-10%",
  },
  textInput: {
    flex: 1,
    fontFamily: "regular",
    marginLeft: 12,
    color: "#1f1f1f",
    height: 55,
  },
  errorInput: {
    position: "absolute",
    left: 0,
    bottom: 3,
    fontFamily: "medium",
    color: "red",
    fontSize: 12,
  },
  inputContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fafafa",
    borderWidth: 1,
    borderColor: "#404040",
    padding: 11,
    paddingLeft: 0,
    borderRadius: 8,
    margin: 3,
    marginBottom: 18,
    height: 55,
  },
  placeholder: {
    flex: 1,
    marginLeft: 12,
    color: "#1f1f1f",
    fontSize: 12,
    fontFamily: "regular",
    height: 55,
  },
  labelInput: {
    fontFamily: "bold",
    fontSize: 14,
    color: "#404040",
  },
  errorInputDescription: {
    position: "absolute",
    left: 0,
    bottom: 3,
    fontFamily: "medium",
    color: "red",
    fontSize: 12,
  },
  inputContainerDescription: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fafafa",
    borderWidth: 1,
    borderColor: "#404040",
    padding: 10,
    paddingLeft: 0,
    borderRadius: 8,
    margin: 3,
    marginBottom: 18,
    height: 145,
  },
  placeholderDescription: {
    marginLeft: 10,
    color: "#1f1f1f",
    fontSize: 12,
    fontFamily: "regular",
    textAlign: "justify",
    height: 130,
    flex: 1,
  },
  textInputDescription: {
    flex: 1,
    width: 300,
    fontFamily: "regular",
    marginLeft: 12,
    color: "#1f1f1f",
    height: 130,
  },
});

export default styles;
