import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  main: {
    flex: 1,
    padding: 20,
    position: "relative",
    zIndex: 100,
  },
  container: {
    flex: 1,
    padding: 20,
    paddingTop: 50,
  },
  title: {
    fontFamily: "thinItalic",
    fontSize: 20,
    marginBottom: 10,
  },
  textInputP: {
    flex: 1,
    fontFamily: "regular",
    // marginLeft: 12,
    color: "#1f1f1f",
    height: 55,
  },
  textInput: {
    flex: 1,
    fontFamily: "regular",
    // marginLeft: 12,
    color: "#1f1f1f",
    height: 55,
  },
  errorInput: {
    position: "absolute",
    left: 2,
    bottom: 0,
    fontFamily: "medium",
    color: "red",
    fontSize: 12,
  },
  errorInputP: {
    position: "absolute",
    left: 2,
    bottom: 0,
    fontFamily: "medium",
    color: "red",
    fontSize: 12,
  },
  inputContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#404040",
    padding: 11,
    borderRadius: 8,
    margin: 3,
    height: 55,
    marginBottom: 15,
  },
  inputContainerP: {
    flex: 1,
    width: 210,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#404040",
    padding: 11,
    borderRadius: 8,
    margin: 3,
    height: 55,
    marginBottom: 15,
  },
  placeholder: {
    flex: 1,
    color: "#1f1f1f",
    fontSize: 12,
    fontFamily: "regular",
  },
  labelInput: {
    fontFamily: "bold",
    fontSize: 14,
    color: "#1f1f1f",
  },
  textInputBot: {
    flex: 1,
    marginLeft: 10,
    color: "#fb8500",
    fontFamily: "light",
  },
  inputContainerBot: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderWidth: 0,
    paddingLeft: 5,
    borderRadius: 8,
    margin: 3,
  },
  placeholderBot: {
    flex: 1,
    marginLeft: 10,
    color: "#8c9199cb",
    fontSize: 11,
    fontFamily: "light",
  },
  inputContainerDescription: {
    flexDirection: "row",
    justifyContent: "center",
    backgroundColor: "#fafafa",
    borderWidth: 0,
    padding: 11,
    borderRadius: 8,
    margin: 3,
    height: 130,
    width: 333,
  },
  placeholderDescription: {
    marginLeft: 10,
    color: "#8c9199cb",
    fontSize: 12,
    fontFamily: "light",
    textAlign: "justify",
    height: 130,
    width: 313,
  },
  textInputDescription: {
    width: "100%",
    padding: "0 10px",
    color: "#fb8500",
    fontFamily: "light",
    textAlign: "justify",
    fontSize: 12,
  },
  labelInputBot: {
    fontFamily: "regular",
    fontSize: 14,
    color: "#1f1f1f",
  },
  modalMain: {
    flex: 1,
    backgroundColor: "white",
    width: "100%",
    height: "100%",
  },
  modalContent: {
    flex: 1,
    justifyContent: "space-between",
    backgroundColor: "white",
    padding: 20,
    width: "100%",
    height: "100%",
  },
  modalBott: {
    marginTop: "41%",
    flex: 0.5,
    alignSelf: "flex-end",
    justifyContent: "flex-end",
  },
  modalTop: {
    flex: 1.3,
  },
  modalMid: {
    flex: 1.7,
  },
  modalContainerCountries: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(52, 52, 52, 0.5)",
  },
  modalTopCountries: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTextCountries: {
    fontFamily: "regular",
    fontSize: 14,
    marginLeft: 5,
  },
  modalContentCountries: {
    backgroundColor: "white",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1f1f1f",
    width: 220,
    height: 400,
  },
  modalTextSelectCountries: {
    fontFamily: "light",
    fontSize: 14,
    color: "#8c9199",
  },
});

export default styles;
